#!/bin/bash
#
# File : CCTK config script Linux/Unix
# Generated by Cerberus
# At Mon 07/27/2015  0:39:16.74
# On HBADGX7900064
#
# Generated by CCTK Configuration Wizard 2.2
#
# Only for supported Linux installations with cctk and srv-admin rpm's installed
# Will need to be root or will require 'sudo' privileges

SCRIPTNAME=`basename $0`
LOG=`basename $0`.log
CCTKPATH=/opt/dell/toolkit/bin
CCTKEXE=cctk
CCTKWHICH=`which cctk 2> /dev/null`


function err {
	echo "Error: ${SCRIPTNAME} : $1"
	exit $2
}


function hlp {
	echo "Help : ${SCRIPTNAME}"
	echo "Applies BIOS config exported from a host system"
	echo "A valid cctk installation is expected"
	echo "Should be run by the root user, or using a 'sudo' command"
	echo "Arguments:"
	echo "-h|--help    this help message"
}


# Handle arguments
if [ "x$2" != "x" ]; then
	hlp
	exit 0
fi

# Check cctk installation presence
if [ "x${CCTKWHICH}" != "x" -a -f "${CCTKWHICH}" -a -x "${CCTKWHICH}" ]; then
	CCTK="${CCTKWHICH}"
elif [ -f "${CCTKPATH}/${CCTKEXE}" -a -x "${CCTKPATH}/${CCTKEXE}" ];  then
	CCTK="${CCTKPATH}/${CCTKEXE}"
else
	err "cctk installation not found" -1
fi


TMPINI=.tmp.cctk.config.ini
if [ -f ${TMPINI} ]; then
	rm -f ${TMPINI}
fi

cat > ${TMPINI} <<HERE
[cctk]
virtualization=enable
vtfordirectio=on
wakeonlan=enablewakeonwlan
HERE


if [ "$(id -u)" != "0" ]; then
   err "Permission Denied - Insufficient priviliges" -1
fi
"${CCTK}" -i ${TMPINI} > ${LOG}
if [ $? == 0 ]; then
	echo "BIOS settings applied successfully"
else
	echo "Error applying BIOS settings."
fi
echo "Details in ${LOG}"
exit $rtn

